name: 'SimplicoAI Simulation'
description: 'Run SimplicoAI Simulation, add necessary environment variables to run the simulation'
inputs:
  github_action_access_token:
    description: 'github token for creating pull request'
    required: true
  github_run_number:
    description: 'github run number'
    required: true
  github_pr_number:
    description: 'github pr number'
    required: false
  github_repo_name:
    description: 'github repo name'
    required: true
  branch_name:
    description: 'branch name'
    required: false
  terraform_root_dir:
    description: 'terraform root directory'
    required: true
  account_id:
    description: 'account to run simulation against'
    required: false
  regions:
    description: 'regions to run simulation against'
    required: false
outputs:
  logs:
    description: "SimplicoAI Action logs"
runs:
    using: 'docker'
    image: 'Dockerfile'
    env:
      TERRAFORM_PATH: ${{ inputs.terraform_root_dir }}
      GITHUB_ACCESS_TOKEN: ${{ inputs.github_action_access_token }}
      GITHUB_RUN_NUMBER: ${{ inputs.github_run_number }}
      GITHUB_PR_NUMBER: ${{ inputs.github_pr_number }}
      REPO_NAME: ${{ inputs.github_repo_name }}
      BRANCH_NAME: ${{ inputs.branch_name }}
      ACCOUNT_ID: ${{ inputs.account_id }}
      REGIONS: ${{ inputs.regions }}
